name: Generate terraform docs
on:
  pull_request:
    paths:
    - 'modules/**/*.tf'
    - '*.tf'

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [., example-spoke-vpc]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ${{ matrix.directory }}
        config-file: .terraform-docs.yml
        git-push: true
        git-commit-message: "terraform-docs: automated action"
